backend:
  name: github
  repo: datascience-logs/ds-blog # Replace with your repo (e.g. user/repo)
  branch: main # Branch to update
  base_url: https://blog-datascience-logs.netlify.app # Replace with your production domain
  auth_endpoint: api/auth # This depends on your OAuth gatekeeper service

local_backend: true # Enables local development via npx decap-cms-proxy-server

publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/posts"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} ({{status}})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly name" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["draft", "published"], default: "draft" }
      - { label: "Tags", name: "tags", widget: "list", hint: "Comma separated list" }
      - { label: "Body", name: "body", widget: "markdown" }

editor:
  preview: true